name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          for i in {1..3}; do pip install -r requirements.txt && break || sleep 10; done

      - name: Verify installed packages
        run: pip freeze

      - name: Check if pytest is installed
        run: pytest --version

      - name: Run tests
        run: pytest
